version: '3.4'

services:
  authorizer:
    build:
      context: ./authorizer
      target: development
    image: 'authorizer:${TAG:-latest}'
    environment:
      - ENVIRONMENT=DEVELOPMENT
      - BROKER_URL=amqp://guest:guest@rabbitmq//
      - READER_HOSTNAME=reader
      - READER_PORT=8000
    volumes:
      - ./authorizer:/usr/src/app/
    networks:
      - mvp
    stdin_open: true
    tty: true

  rabbitmq:
    image: 'rabbitmq:3.7-management-alpine'
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - mvp

networks:
  mvp:
    external: true
