version: "3.4"

services:
  authorizer-test:
    build:
      context: ./authorizer
      target: development
    image: 'peer-mountain01:5005/teleferic-mvp/authorizer/test:${TAG:-latest}'
    environment:
      - ENVIRONMENT=TEST
      - BROKER_URL=rabbitmq-proxy
      - READER_HOSTNAME=reader
      - READER_PORT=8000
    volumes:
      - ./authorizer:/usr/src/app/
